version: "3.7"
services:
  local-php7.4-run:
#    image: local-php-run:7.4
    build:
      context: .
      dockerfile: 7.4/Dockerfile
#    environment: 
#      - COMPOSER_GITLAB_TOKEN=xxxxx
#      - COMPOSER_GITHUB_TOKEN=xxxxx
  local-php8.0-run:
#    image: local-php-run:8.0
    build:
      context: .
      dockerfile: 8.0/Dockerfile
  local-php8.1-run:
#    image: local-php-run:8.1
    build:
      context: .
      dockerfile: 8.1/Dockerfile
